from ossapi import *
from os import getenv
from dotenv import load_dotenv
load_dotenv()
api = OssapiV2(int(getenv('OSUAPI_ID')), getenv('OSUAPI_TOKEN'))

print(api.beatmapset_discussion_posts().discussions[0].message_type)
print(api.user_recent_activity(12092800)[0].created_at)
print(api.spotlights()[0].name)
print(api.user_beatmaps(user_id=12092800, type_="most_played")[0].count)
print(api.user_kudosu(user_id=3178418)[0].action)
print(api.beatmap_scores(beatmap_id=1981090).scores[0].id)
print(api.beatmap(beatmap_id=1981090).max_combo)
print(api.ranking("osu", RankingType.PERFORMANCE, country="US").ranking[0].user.username)
print(api.user_scores(15493367, "best")[0].pp)
print(api.beatmap(beatmap_id=221777).last_updated)
print(api.beatmap_user_score(beatmap_id=221777, user_id=2757689).score.mods)
print(api.search(query="Lulu x Pix").users.data[0].username)
print(api.comment(comment_id=1).comments[0].message)
#print(api.download_score(mode="osu", score_id=2797309065))
print(api.search_beatmapsets(query="the big black").beatmapsets[0].title)
print(api.beatmapset_events(types=[BeatmapsetEventType.ISSUE_REOPEN]).events[0].type)
print(api.user(12092800).playstyle)
print(api.wiki_page("en", "Welcome").available_locales)
print(api.changelog_build("stable40", "20210520.2").users)
print(api.changelog_listing().builds[0].display_version)
print(api.changelog_lookup("lazer").changelog_entries[0].github_pull_request_id)
print(api.forum_topic(141240).posts[0].forum_id)
print(api.beatmapset_discussion_votes().votes[0].score)
print(api.score(mode="osu", score_id=2797309065).beatmap)
print(api.news_listing(year=2021).news_posts[0].author)
print(api.news_post(1025, key="id"))
#print(api.friends()[0].username)
print(api.seasonal_backgrounds().backgrounds[0].url)

response = api.ranking("osu", RankingType.PERFORMANCE)
for ranking in response.ranking:
    print(f"global #{ranking.global_rank}: {ranking.user.username}")